"""add retry and idempotency columns

Revision ID: bd460aa21726
Revises: dfdcb404a58e
Create Date: 2026-07-28 11:24:12.130671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd460aa21726'
down_revision: Union[str, Sequence[str], None] = 'dfdcb404a58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tasks', sa.Column('max_attempts', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('tasks', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('last_error', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_tasks_idempotency_key'), 'tasks', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_idempotency_key'), table_name='tasks')
    op.drop_column('tasks', 'last_error')
    op.drop_column('tasks', 'idempotency_key')
    op.drop_column('tasks', 'max_attempts')
    op.drop_column('tasks', 'attempts')
    # ### end Alembic commands ###
